# Example Config that uses almost all values

alg: DRQV2
alg_kwargs:
  tau: 0.01
  critic_freq: 1
  actor_freq: 1
  target_freq: 1
  noise_clip: 0.3
  std_schedule: [1.0, 0.1, 500000]
  init_steps: 4000

optim: Adam
optim_kwargs:
  lr: 0.0001

network: ActorCriticPolicy
network_kwargs:
  actor_class: DRQV2Actor
  actor_kwargs:
    feature_dim: 50
    hidden_dim: 1024
  critic_class: DRQV2Critic
  critic_kwargs:
    feature_dim: 50
    hidden_dim: 1024
  encoder_class: DRQV2Encoder

batch_size: null # Use serial replay buffer
collate_fn: null # The collate function passed to the dataloader. None uses pytorch default.
checkpoint: null # A checkpoint to initialize the network from.

env: CheetahRun-vision-v0

dataset: ReplayBuffer
dataset_kwargs:
  discount: 0.99
  nstep: 3
  capacity: 1000000
  fetch_every: 1000
  batch_size: 256

processor: RandomShiftsAug # Add in the data augmentations!

train_kwargs: # Arguments given to Algorithm.train
  total_steps: 3100000 # The total number of steps to train
  log_freq: 250 # How often to log values
  eval_freq: 10000 # How often to run evals
  eval_ep: 10 # Number of enviornment episodes to run for evaluation, or -1 if none should be run.
  loss_metric: reward # The validation metric that determines when to save the "best_checkpoint"
  workers: 4 # Number of dataloader workers.
  profile_freq: 200
