name: ipl
channels:
  - pytorch
  - default
dependencies:
  - python=3.10

  # Development
  - black
  - isort
  - flake8
  - conda-forge::pre-commit

  # pytorch
  - pytorch
  - cpuonly
  - torchvision
  - torchtext
  - torchaudio

  # NP Family
  - numpy
  - scipy
  - scikit-image
  - numba # For Robosuite

  # IO
  - imageio
  - pillow
  - pyyaml
  - cloudpickle
  - h5py
  - absl-py
  - pyparsing

  # Plotting
  - tensorboard
  - pandas
  - matplotlib
  - seaborn

  # Other
  - pytest
  - tqdm
  - future

  - pip
  - pip:
      - gym==0.23.1
      - mujoco-py<2.2,>=2.1
      - git+https://github.com/rlworkgroup/metaworld.git@master#egg=metaworld
      - git+https://github.com/Farama-Foundation/d4rl@master#egg=d4rl
