# Example Config that uses almost all values

alg: SAC
alg_kwargs:
  tau: 0.005
  init_temperature: 0.1
  critic_freq: 1
  actor_freq: 1
  target_freq: 2
  init_steps: 9000

optim: Adam
optim_kwargs:
  lr: 0.0003

network: ActorCriticPolicy # Use the Actor Critic Class so we can finetune later!
network_kwargs:
  actor_class: DiagonalGaussianMLPActor
  actor_kwargs:
    hidden_layers: [256, 256, 256]
    log_std_bounds: [-5, 2]
    ortho_init: true
  critic_class: ContinuousMLPCritic
  critic_kwargs:
    hidden_layers: [256, 256, 256]
    ensemble_size: 2
    ortho_init: true

batch_size: null
collate_fn: null # The collate function passed to the dataloader. None uses pytorch default.
checkpoint: null # A checkpoint to initialize the network from.

env: null
env_kwargs:
  goal: null
  state_noise: 0.0

dataset: ReplayBuffer
dataset_kwargs:
  discount: 0.99
  nstep: 1
  capacity: 800000
  fetch_every: 500
  batch_size: 512

processor: null

train_kwargs: # Arguments given to Algorithm.train
  total_steps: 800000 # The total number of steps to train
  log_freq: 500 # How often to log values
  eval_freq: 10000 # How often to run evals
  eval_fn: eval_policy
  eval_kwargs:
    num_ep: 15 # Number of enviornment episodes to run for evaluation
  loss_metric: reward # The validation metric that determines when to save the "best_checkpoint"
  workers: 0 # Number of dataloader workers.
  profile_freq: 250
