alg: PEBBLE
alg_kwargs:
  unsup_steps: 0
  random_steps: 10000
  reward_freq: 5000
  max_feedback: 8000
  init_feedback_size: 40
  reward_batch_size: 64
  segment_size: 25
  reward_epochs: 0.95

optim: Adam
optim_kwargs:
  lr: 0.0003

network: ActorCriticRewardPolicy
network_kwargs:
  actor_class: DiagonalGaussianMLPActor
  actor_kwargs:
    hidden_layers: [256, 256, 256]
    log_std_bounds: [-5, 2]
    ortho_init: true
  critic_class: ContinuousMLPCritic
  critic_kwargs:
    hidden_layers: [256, 256, 256]
    ensemble_size: 2
    ortho_init: true
  reward_class: ContinuousMLPCritic
  reward_kwargs:
    ensemble_size: 3
    hidden_layers: [256, 256, 256]
    act: ["import", "torch.nn", "LeakyReLU"]
    output_act: ["import", "torch.nn", "Tanh"]

env: mw_door-close-v2

dataset: ReplayBuffer
dataset_kwargs:
  distributed: False
  discount: 0.99
  nstep: 1
  capacity: 1000000
  fetch_every: 500
  batch_size: 256

processor: null

trainer_kwargs: # Arguments given to Algorithm.train
  total_steps: 1000000 # The total number of steps to train
  log_freq: 500 # How often to log values
  eval_freq: 10000 # How often to run evals
  eval_fn: eval_policy
  eval_kwargs:
    num_ep: 25 # Number of enviornment episodes to run for evaluation
  loss_metric: reward # The validation metric that determines when to save the "best_checkpoint"
  train_dataloader_kwargs:
    num_workers: 0
    batch_size: null
    collate_fn: null
  profile_freq: 500

checkpoint: null
seed: null
