# Example Config that uses almost all values

alg: IHLearn
alg_kwargs:
  tau: 0.005
  init_temperature: 0.1
  target_freq: 2
  init_steps: 1000
  reward_freq: 500
  reward_epochs: 0.95
  max_feedback: 8000
  init_feedback_size: 40
  reward_batch_size: 128
  segment_size: 25
  feedback_schedule: constant
  feedback_sample_multiplier: 10

optim: Adam
optim_kwargs:
  lr: 0.0003

network: ActorCriticPolicy
network_kwargs:
  actor_class: DiagonalGaussianMLPActor
  actor_kwargs:
    hidden_layers: [256, 256, 256]
    log_std_bounds: [-5, 2]
    ortho_init: true
  critic_class: ContinuousMLPCritic
  critic_kwargs:
    hidden_layers: [256, 256, 256]
    ensemble_size: 3
    ortho_init: true

batch_size: null
collate_fn: null
checkpoint: null
seed: null

env: mw_door-close-v2

dataset: ReplayBuffer
dataset_kwargs:
  distributed: False
  discount: 0.99
  nstep: 1
  capacity: 1000000
  fetch_every: 500
  batch_size: 256

processor: null

train_kwargs: # Arguments given to Algorithm.train
  total_steps: 1000000 # The total number of steps to train
  log_freq: 1000 # How often to log values
  eval_freq: 10000 # How often to run evals
  eval_fn: eval_policy
  eval_kwargs:
    num_ep: 15 # Number of enviornment episodes to run for evaluation
  loss_metric: reward # The validation metric that determines when to save the "best_checkpoint"
  workers: 0 # Number of dataloader workers.
  profile_freq: 1000
