alg: IHLearnAWAC
alg_kwargs:
  tau: 0.005
  target_freq: 1
  beta: 0.2
  chi2_coeff: 0.5

optim: Adam
optim_kwargs:
  lr: 0.0003

network: ActorCriticPolicy
network_kwargs:
  actor_class: DiagonalGaussianMLPActor
  actor_kwargs:
    log_std_bounds: [-5, 2]
    output_act: ["import", "torch.nn", "Tanh"]
    state_dependent_log_std: False
    log_std_tanh: False
    squash_normal: False
  critic_class: ContinuousMLPCritic
  critic_kwargs:
    ensemble_size: 1
  hidden_layers: [256, 256, 256]
  ortho_init: True

eval_env: mw_door-close-v2

dataset: PairwiseComparisonDataset
dataset_kwargs:
  path: ../datasets/test/pairwise.npz
  capacity: null
  segment_size: 25
  discount: 0.99
  subsample_size: 16
  batch_size: 16


trainer_kwargs: # Arguments given to Algorithm.train
  total_steps: 200000 # The total number of steps to train
  log_freq: 500 # How often to log values
  eval_freq: 2500 # How often to run evals
  eval_fn: eval_policy
  eval_kwargs:
    num_ep: 10 # Number of enviornment episodes to run for evaluation
  loss_metric: reward # The validation metric that determines when to save the "best_checkpoint"
  train_dataloader_kwargs:
    num_workers: 0
    batch_size: null
    collate_fn: null
  profile_freq: 500

seed: null
